package com.example.hardcodedcertdemo

object CertHolder {
    const val CERT = """
        -----BEGIN CERTIFICATE-----
        MIIDdzCCAl+gAwIBAgIEbOeU8zANBgkqhkiG9w0BAQsFADBvMQswCQYDVQQGEwJD
        TjELMAkGA1UECBMCQkoxCzAJBgNVBAcTAkJKMQswCQYDVQQKEwJUUzELMAkGA1UE
        CxMCVFQxCzAJBgNVBAMTAlRTMRMwEQYDVQQpEwpURVNUQ0VSVDAeFw0xNzA2MDEx
        MjAwMDBaFw0xODA2MDExMjAwMDBaMG8xCzAJBgNVBAYTAkNOMQswCQYDVQQIEwJC
        SjELMAkGA1UEBxMCQkoxCzAJBgNVBAoTAlRTMQswCQYDVQQLEwJUVDELMAkGA1UE
        AxMCVFMyEzARBgoJkiaJk/IsZAEZFgNVBApTCVRFU1RDQ0VSVDAwggEiMA0GCSqG
        SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCkEKJnb5HlF7gzW5bhMQ==
        -----END CERTIFICATE-----
    """
}